steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/alchemist-agent-engine:$BUILD_ID', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/alchemist-agent-engine:$BUILD_ID']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'alchemist-agent-engine'
  - '--image'
  - 'gcr.io/$PROJECT_ID/alchemist-agent-engine:$BUILD_ID'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--memory'
  - '1Gi'
  - '--cpu'
  - '1'
  - '--min-instances'
  - '0'
  - '--max-instances'
  - '10'
  - '--timeout'
  - '300s'
  - '--set-env-vars'
  - 'ALCHEMIST_MODEL=gpt-4.1,ENVIRONMENT=production,PYTHONPATH=/app,PROMPT_ENGINEER_API_URL=https://alchemist-prompt-engine-851487020021.us-central1.run.app,MCP_CONFIG_GENERATOR_URL=https://mcp-config-generator-851487020021.us-central1.run.app,FIREBASE_STORAGE_BUCKET=$PROJECT_ID.appspot.com'
  - '--set-secrets'
  - 'OPENAI_API_KEY=OPENAI_API_KEY:latest'
images:
- 'gcr.io/$PROJECT_ID/alchemist-agent-engine:$BUILD_ID'
timeout: '3600s'
