steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/alchemist-monitor-service:$BUILD_ID', '.']
    
  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/alchemist-monitor-service:$BUILD_ID']
    
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'alchemist-monitor-service'
      - '--image=gcr.io/$PROJECT_ID/alchemist-monitor-service:$BUILD_ID'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--concurrency=100'
      - '--max-instances=10'
      - '--min-instances=1'
      - '--set-env-vars=ENVIRONMENT=production'

# Store the built image
images:
  - 'gcr.io/$PROJECT_ID/alchemist-monitor-service:$BUILD_ID'

# Options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout
timeout: '1200s'