# Google Cloud Build configuration for Agent Tuning Service

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/alchemist-agent-tuning:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/alchemist-agent-tuning:latest'
      - '.'
    id: 'build-image'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/alchemist-agent-tuning:$COMMIT_SHA'
    id: 'push-image-sha'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/alchemist-agent-tuning:latest'
    id: 'push-image-latest'
    waitFor: ['build-image']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'alchemist-agent-tuning'
      - '--image=gcr.io/$PROJECT_ID/alchemist-agent-tuning:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=3600'
      - '--concurrency=80'
      - '--max-instances=10'
      - '--set-env-vars=TUNING_ENVIRONMENT=production,TUNING_FIREBASE_PROJECT_ID=$PROJECT_ID'
      - '--set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest'
    id: 'deploy-service'
    waitFor: ['push-image-sha']

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/alchemist-agent-tuning:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/alchemist-agent-tuning:latest'

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout
timeout: '1200s'

# Substitutions
substitutions:
  _SERVICE_NAME: 'alchemist-agent-tuning'
  _REGION: 'us-central1'