# Google Cloud Build configuration for Global Narrative Framework
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/global-narrative-framework:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/global-narrative-framework:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/global-narrative-framework:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/global-narrative-framework:latest'

  # Deploy backend service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'global-narrative-framework'
      - '--image'
      - 'gcr.io/$PROJECT_ID/global-narrative-framework:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '5'
      - '--min-instances'
      - '0'
      - '--timeout'
      - '900'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,FIREBASE_PROJECT_ID=$PROJECT_ID,PYTHONPATH=/app'
      - '--set-secrets'
      - 'OPENAI_API_KEY=OPENAI_API_KEY:latest'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/global-narrative-framework:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/global-narrative-framework:latest'

# Options for the build
options:
  logging: CLOUD_LOGGING_ONLY
  
# Timeout for the entire build
timeout: '1200s'