version: '3.8'

services:
  universal-deployment-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REGION=${REGION:-us-central1}
    volumes:
      - ./firebase-credentials.json:/app/firebase-credentials.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s