# Cloud Build configuration for agent-template deployments
# This builds Docker images for individual agents using the standardized Dockerfile.agent-template
# Usage: Used by deploy_agent_with_progress.py for efficient agent deployments

steps:
  # Step 1: Build the agent Docker image with build args
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-agent-image'
    args:
      - 'build'
      - '--file=Dockerfile.agent-template'
      - '--build-arg=AGENT_ID=${_AGENT_ID}'
      - '--build-arg=PROJECT_ID=${PROJECT_ID}'
      - '--tag=gcr.io/${PROJECT_ID}/agent-${_AGENT_ID}:latest'
      - '--tag=gcr.io/${PROJECT_ID}/agent-${_AGENT_ID}:${BUILD_ID}'
      - '--tag=gcr.io/${PROJECT_ID}/agent-${_AGENT_ID}:${_TIMESTAMP}'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'

  # Step 2: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/agent-${_AGENT_ID}:latest'
    waitFor: ['build-agent-image']

  # Step 3: Push the build ID tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-build-id'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/agent-${_AGENT_ID}:${BUILD_ID}'
    waitFor: ['build-agent-image']

  # Step 4: Push the timestamp tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-timestamp'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/agent-${_AGENT_ID}:${_TIMESTAMP}'
    waitFor: ['build-agent-image']

# Substitutions for dynamic values
substitutions:
  # These will be provided when triggering the build
  _AGENT_ID: 'default-agent'  # Will be overridden with actual agent_id
  _TIMESTAMP: '${BUILD_ID}'   # Will be overridden with timestamp

# Build timeout (20 minutes)
timeout: '1200s'

# Options for build configuration
options:
  # Use high-performance machine for faster builds
  machineType: 'E2_HIGHCPU_8'
  
  # Enable build optimization
  substitution_option: 'ALLOW_LOOSE'
  
  # Disk size for build
  diskSizeGb: 50
  
  # Enable build logs
  logging: 'CLOUD_LOGGING_ONLY'

# Images to be produced (for reference)
images:
  - 'gcr.io/${PROJECT_ID}/agent-${_AGENT_ID}:latest'
  - 'gcr.io/${PROJECT_ID}/agent-${_AGENT_ID}:${BUILD_ID}'
  - 'gcr.io/${PROJECT_ID}/agent-${_AGENT_ID}:${_TIMESTAMP}'

# Tags for the build
tags:
  - 'agent-deployment'
  - 'agent-${_AGENT_ID}'
  - 'automated-build'