// Shared services configuration for Alchemist platform
export const services = [
  {
    name: 'Agent Engine',
    url: 'https://alchemist-agent-engine-851487020021.us-central1.run.app',
    description: 'Core orchestration service for the Alchemist AI platform',
    type: 'Core Service',
    version: '1.0.0',
    port: 8080,
    healthEndpoint: '/health',
    icon: '🚀',
  },
  {
    name: 'Knowledge Vault',
    url: 'https://alchemist-knowledge-vault-851487020021.us-central1.run.app',
    description: 'Document processing and semantic search service',
    type: 'Data Service',
    version: '2.0.0',
    port: 8080,
    healthEndpoint: '/health',
    icon: '📚',
  },
  {
    name: 'Agent Bridge',
    url: 'https://alchemist-agent-bridge-851487020021.us-central1.run.app',
    description: 'WhatsApp Business integration service',
    type: 'Integration Service',
    version: '1.0.0',
    port: 8080,
    healthEndpoint: '/health',
    icon: '🌉',
  },
  {
    name: 'Agent Launcher',
    url: 'https://alchemist-agent-launcher-851487020021.us-central1.run.app',
    description: 'Agent deployment automation service',
    type: 'Infrastructure Service',
    version: '1.0.0',
    port: 8080,
    healthEndpoint: '/health',
    icon: '🚀',
  },
  {
    name: 'Tool Forge',
    url: 'https://alchemist-tool-forge-851487020021.us-central1.run.app',
    description: 'MCP server management and deployment',
    type: 'Management Service',
    version: '1.0.0',
    port: 8080,
    healthEndpoint: '/health',
    icon: '🔨',
  },
  {
    name: 'Agent Studio',
    url: 'https://alchemist-agent-studio-851487020021.us-central1.run.app',
    description: 'Web application interface for agent management',
    type: 'Frontend Service',
    version: '1.0.0',
    port: 3000,
    healthEndpoint: '/health',
    icon: '🎨',
  },
  {
    name: 'Prompt Engine',
    url: 'https://alchemist-prompt-engine-851487020021.us-central1.run.app',
    description: 'AI prompt processing and optimization service',
    type: 'AI Service',
    version: '1.0.0',
    port: 8080,
    healthEndpoint: '/health',
    icon: '🧠',
  },
  {
    name: 'Sandbox Console',
    url: 'https://alchemist-sandbox-console-851487020021.us-central1.run.app',
    description: 'Interactive testing and development environment',
    type: 'Development Service',
    version: '1.0.0',
    port: 8080,
    healthEndpoint: '/health',
    icon: '🧪',
  },
  {
    name: 'MCP Config Generator',
    url: 'https://alchemist-mcp-config-generator-851487020021.us-central1.run.app',
    description: 'MCP configuration generation service',
    type: 'Configuration Service',
    version: '1.0.0',
    port: 8080,
    healthEndpoint: '/health',
    icon: '⚙️',
  },
];